### ISSUE TITLE
Count garbage collections per run

### ISSUE THREAD

**Issue by hadley** [jimhester/bench#10]
Using something like this:

```R
count_gc <- function() {
  complete <- FALSE
  reg.finalizer(environment(), function(e) complete <<- TRUE)

  i <- 0
  fin <- function(e) {
    i <<- i + 1
    if (!identical(complete, TRUE)) {
      reg.finalizer(environment(), fin)
    }
  }
  fin()

  function() i
}

gcs <- count_gc()
```

Adapted from https://gist.github.com/wch/a2775667274dbd2e81325a43bc48f1a4

**Comment by hadley** [comment]
I added a print statement in `fin()` to verify that this strategy does ensure the finaliser stops running when `gcs()` is gc'd.

**Comment by hadley** [comment]
I wonder if we could detect different levels of GC by nesting the finalised environment within a stack of other environments

**Comment by jimhester** [comment]
So empirically it looks like the finalizers are only called on level 2 gcs, and `?reg.finalizer` says

> Finalizers are scheduled at garbage collection but only run at a relatively safe time
  thereafter.

So I don't think this method is accurate enough to be useful for this purpose.

Another approach would be to use `gcinfo()`. It likely would be too much overhead for the timing runs, but we could probably do it with the first evaluation...

**Comment by jimhester** [comment]
My new hypothesis is that the multi-model distribution is related to levels of memory hierarchy / memory pages rather than gc levels. The gcs seem to be only the handful of runs with very high execution times.
