### ISSUE TITLE
Run benchmarks in a separate process

### ISSUE THREAD

**Issue by jimhester** [jimhester/bench#2]
Likely with callr

Avoids issues with existing environment changing benchmark outputs, also allows you to potentially use different package libraries for benchmarks.

**Comment by jimhester** [comment]
Going to let this ruminate for now, as @gaborcsardi mentioned it would make this a fair amount more difficult.

**Comment by gaborcsardi** [comment]
I think it has some good use cases, like comparing different package versions, etc. but yeah, it does create some complications, some maybe it should not be the default.

**Comment by jimhester** [comment]
I think I am going to close this, I think often the benchmarks will be run with reprex, so you already get this from that.
